In [2]:
import pandas as pd

In [3]:
players = pd.read_csv('./nba_players.csv')

In [4]:
players.head()

,Unnamed: 0,Name,Games Played,MIN,PTS,3P%,FT%,OREB,DREB,AST,...,Birth_Place,Birthdate,Collage,Experience,Height,Pos,Team,Weight,BMI,url
0,0,AJ Price,26,324,133,26.3,66.7,6,26,46,...,us,"October 7, 1986",University of Connecticut,5,185.0,PG,PHO,81.45,23.798393,https://raw.githubusercontent.com/nonameable/e...
1,1,Aaron Brooks,82,1885,954,38.7,83.3,32,134,261,...,us,"January 14, 1985",University of Oregon,6,180.0,PG,CHI,72.45,22.361111,https://raw.githubusercontent.com/nonameable/e...
2,2,Aaron Gordon,47,797,243,27.1,72.1,46,123,33,...,us,"September 16, 1995",University of Arizona,R,202.5,PF,ORL,99.00,24.142661,https://raw.githubusercontent.com/nonameable/e...
3,3,Adreian Payne,32,740,213,11.1,65.2,48,114,30,...,us,"February 19, 1991",Michigan State University,R,205.0,PF,ATL,106.65,25.377751,https://raw.githubusercontent.com/nonameable/e...
4,4,Al Horford,76,2318,1156,30.6,75.9,131,413,244,...,do,"June 3, 1986",University of Florida,7,205.0,C,ATL,110.25,26.234384,https://raw.githubusercontent.com/nonameable/e...

In [5]:
players['id'] = players.index

In [6]:
players.head()

,Unnamed: 0,Name,Games Played,MIN,PTS,3P%,FT%,OREB,DREB,AST,...,Birthdate,Collage,Experience,Height,Pos,Team,Weight,BMI,url,id
0,0,AJ Price,26,324,133,26.3,66.7,6,26,46,...,"October 7, 1986",University of Connecticut,5,185.0,PG,PHO,81.45,23.798393,https://raw.githubusercontent.com/nonameable/e...,0
1,1,Aaron Brooks,82,1885,954,38.7,83.3,32,134,261,...,"January 14, 1985",University of Oregon,6,180.0,PG,CHI,72.45,22.361111,https://raw.githubusercontent.com/nonameable/e...,1
2,2,Aaron Gordon,47,797,243,27.1,72.1,46,123,33,...,"September 16, 1995",University of Arizona,R,202.5,PF,ORL,99.00,24.142661,https://raw.githubusercontent.com/nonameable/e...,2
3,3,Adreian Payne,32,740,213,11.1,65.2,48,114,30,...,"February 19, 1991",Michigan State University,R,205.0,PF,ATL,106.65,25.377751,https://raw.githubusercontent.com/nonameable/e...,3
4,4,Al Horford,76,2318,1156,30.6,75.9,131,413,244,...,"June 3, 1986",University of Florida,7,205.0,C,ATL,110.25,26.234384,https://raw.githubusercontent.com/nonameable/e...,4

In [7]:
file_name = "nba_players_with_id.csv"
players.to_csv(file_name, sep=',', encoding='utf-8')